In [18]:
import collections
import numpy as np
from tqdm import tqdm
import os
import random
import torch
from SPAIC import spaic
import torch.nn.functional as F
from SPAIC.spaic.Learning.Learner import Learner
from SPAIC.spaic.Library.Network_saver import network_save
from SPAIC.spaic.Library.Network_loader import network_load
from SPAIC.spaic.IO.Dataset import MNIST as dataset
from SPAIC.spaic.IO.Dataset import CUSTOM_MNIST
import gymnasium as gym
import matplotlib.pyplot as plt
from torch.utils.tensorboard import SummaryWriter



In [19]:
torch.rand(1,5)

tensor([[0.1444, 0.6497, 0.9524, 0.5155, 0.8116]])

In [65]:
a = [torch.rand(1,5) for _ in range(3)]
b = [torch.rand(1,5) for _ in range(3)]

In [66]:
a

[tensor([[0.1329, 0.7132, 0.7283, 0.0837, 0.3327]]),
 tensor([[0.3327, 0.7510, 0.9846, 0.2523, 0.5098]]),
 tensor([[0.1014, 0.2670, 0.8109, 0.5855, 0.4704]])]

In [71]:
a[0][0][0].item()

0.13293927907943726

In [83]:
a = [torch.tensor(5, device='cuda'), torch.tensor(4, device='cuda')]
a

[tensor(5, device='cuda:0'), tensor(4, device='cuda:0')]

In [86]:
b =torch.argmax(torch.tensor(a))
b

tensor(0)

In [90]:
c = torch.tensor(0, device='cuda')
c

tensor(0, device='cuda:0')

In [91]:
b == c

tensor(True, device='cuda:0')

In [36]:
sum(buffer[0])

tensor([[1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1.,
         1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 2., 1., 1., 1., 0., 0.,
         1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 2., 0., 0., 0., 0., 1.,
         1., 0., 0., 1., 1., 0., 0., 1., 1., 2., 0., 0., 0., 0., 1., 0., 0., 1.,
         1., 1., 0., 1., 0., 1., 2., 0., 2., 0., 0., 3., 1., 0., 1., 3., 1., 0.,
         0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]], device='cuda:0')

In [37]:
sum(buffer[1])

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 6., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 6., 0., 0., 0., 0., 0., 0., 0., 0.]], device='cuda:0')

In [40]:
len(buffer)

2

In [55]:
a = [sum(buffer[i]) / len(buffer[i]) for i in range(len(buffer))] 
a

[tensor([[0.5000, 0.5000, 0.0000, 0.5000, 0.5000, 0.0000, 0.0000, 0.5000, 0.0000,
          0.5000, 0.0000, 0.5000, 0.5000, 0.5000, 0.0000, 0.0000, 0.5000, 0.5000,
          0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5000, 0.5000,
          0.0000, 0.0000, 0.0000, 1.0000, 0.5000, 0.5000, 0.5000, 0.0000, 0.0000,
          0.5000, 0.0000, 0.0000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5000,
          0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5000,
          0.5000, 0.0000, 0.0000, 0.5000, 0.5000, 0.0000, 0.0000, 0.5000, 0.5000,
          1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5000, 0.0000, 0.0000, 0.5000,
          0.5000, 0.5000, 0.0000, 0.5000, 0.0000, 0.5000, 1.0000, 0.0000, 1.0000,
          0.0000, 0.0000, 1.5000, 0.5000, 0.0000, 0.5000, 1.5000, 0.5000, 0.0000,
          0.0000, 0.0000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000]], device='cuda:0'),
 tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.

In [58]:
torch.cat((a),0)

tensor([[0.5000, 0.5000, 0.0000, 0.5000, 0.5000, 0.0000, 0.0000, 0.5000, 0.0000,
         0.5000, 0.0000, 0.5000, 0.5000, 0.5000, 0.0000, 0.0000, 0.5000, 0.5000,
         0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5000, 0.5000,
         0.0000, 0.0000, 0.0000, 1.0000, 0.5000, 0.5000, 0.5000, 0.0000, 0.0000,
         0.5000, 0.0000, 0.0000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5000,
         0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5000,
         0.5000, 0.0000, 0.0000, 0.5000, 0.5000, 0.0000, 0.0000, 0.5000, 0.5000,
         1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5000, 0.0000, 0.0000, 0.5000,
         0.5000, 0.5000, 0.0000, 0.5000, 0.0000, 0.5000, 1.0000, 0.0000, 1.0000,
         0.0000, 0.0000, 1.5000, 0.5000, 0.0000, 0.5000, 1.5000, 0.5000, 0.0000,
         0.0000, 0.0000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0

In [61]:
torch.argmax(torch.cat((a),0), 0)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0], device='cuda:0')

In [53]:
torch.cat((x,x,x), 0)

tensor([[-1.0626, -0.1217,  1.4705],
        [ 1.4965, -2.2022, -0.8153],
        [-1.0626, -0.1217,  1.4705],
        [ 1.4965, -2.2022, -0.8153],
        [-1.0626, -0.1217,  1.4705],
        [ 1.4965, -2.2022, -0.8153]])

In [62]:
a= [1,2,3,4]
np.argmax(np.array(a))

3

In [63]:
with torch.no_grad(): 
    a = [0,0,0]
    print(a)


[0, 0, 0]


In [64]:
a

[0, 0, 0]